site_name: FlexCloud
site_author: TUMFTM
repo_url: https://github.com/TUMFTM/FlexCloud
site_url: https://TUMFTM.github.io/FlexCloud
site_description: Direct, modular georeferencing and drift-correction of point cloud maps

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

use_directory_urls: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TUMFTM/FlexCloud

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs"]
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

copyright: Copyright &copy; 2025 - 2026 TUMFTM

extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Test Data & Visualization: test-data.md
  - Functionality & References: functionality.md
  - Version Details:
      - Overview: version_details/index.md
      - Latest: version_details/latest.md
      # VERSION_NAV_START
      - version_details/1.0.2.md
      - version_details/1.0.1.md
      - version_details/1.0.0.md
      # VERSION_NAV_END
